### ISSUE TITLE
Problem Starting The Site To Run 

### ISSUE THREAD

**Issue by nabiloo19** [santosfrancisco/gatsby-starter-cv#40]
This is what I get whenever I run either `npm run develop` or `gatsby develop`:
`
> gatsby-starter-cv@0.0.1 develop C:\Users\nabil\Documents\workspace\Portfolio - Nabil\my-default-start
> gatsby develop                                                                                       
                                                                                                       
`C:\Users\nabil\Documents\workspace\Portfolio - Nabil\my-default-starter\node_modules\yoga-layout-prebui
        throw ex;                                                                                      
        ^
`                                                                                              
    `                                                                                             
Error: listen EADDRINUSE: address already in use 127.0.0.1:8000                                        
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)                                         
    at listenInCluster (net.js:1357:12)                                                                
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1496:7)                                       
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:10)                                      
Emitted 'error' event on Server instance at:                                                           
    at emitErrorNT (net.js:1336:8)                                                                     
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {                             
  code: 'EADDRINUSE',                                                                                  
  errno: 'EADDRINUSE',                                                                                 
  syscall: 'listen',                                                                                   
  address: '127.0.0.1',                                                                                
  port: 8000                                                                                           
}                                                                                                      
npm ERR! code ELIFECYCLE                                                                               
npm ERR! errno 7                                                                                       
npm ERR! gatsby-starter-cv@0.0.1 develop: `gatsby develop`                                        
`npm ERR! Exit status 7                                                                                 
npm ERR!                                                                                               
npm ERR! Failed at the gatsby-starter-cv@0.0.1 develop script.                                         
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`                                                                                                      
npm ERR! A complete log of this run can be found in:                                                   
npm ERR!     C:\Users\nabil\AppData\Roaming\npm-cache\_logs\2020-07-18T13_35_55_155Z-debug.log`

**Comment by santosfrancisco** [comment]
@nabiloo19 , good afternoon! All right? Hope so. I just tested it here and had no problem executing the project. I noticed that in the error message it states that port 8000 is already in use. Was there really nothing already running on this port? If there was something running and the port was still busy even after finishing it, it could be that looking for the process using this port (`lsof -i: 8000`) and killing it, solve it.
