### ISSUE TITLE
Replace gatsby-plugin-google-analytics for gatsby-plugin-google-gtag

### ISSUE THREAD

**Issue by abeledovictor** [santosfrancisco/gatsby-starter-cv#46]
The old gatsby-plugin-google-analytics is not working on google analytics. I can submit a PR for it if you want.

Thanks for this amazing template

**Comment by santosfrancisco** [comment]
Hello, @abeledovictor  ! How are you? I hope you're well! Your contribution would be most welcome. Thanks!
