### ISSUE TITLE
Error: Command failed with exit code 128

### ISSUE THREAD

**Issue by Mayyyyyyyy** [santosfrancisco/gatsby-starter-cv#52]
Cloning into 'my-default-starter'...
fatal: unable to access 'https://github.com/santosfrancisco/gatsby-starter-cv.git/': Libr
 ERROR 

Command failed with exit code 128: git clone
https://github.com/santosfrancisco/gatsby-starter-cv.git my-default-starter --recursive
--depth=1

  Error: Command failed with exit code 128: git clone https://github.com/santosfrancisco/
  gatsby-starter-cv.git my-default-starter --recursive --depth=1

**Comment by santosfrancisco** [comment]
Hello @Mayyyyyyyy , I did several tests here and I had no problem cloning the repository. Maybe this can help you https://github.com/gatsbyjs/gatsby/issues/20003

![image](https://user-images.githubusercontent.com/15852005/109438269-fc3abe00-7a07-11eb-9e76-98628b5449e1.png)

**Comment by Mayyyyyyyy** [comment]
Yes, no problem with 'gatsby-starter-cv'. It's about npm permission. Because of this reason, I can't
 use Gatsby. I've tried solutions whatever I can find, but they all failed. Anyway, thanks for your answer.
